### ISSUE TITLE
default.sh: line 3: /app/start.sh: No such file or directory

### ISSUE THREAD

**Issue by berserkwarwolf** [marmotteio/marmotteio#1]
I can't run the docker container.

Docker Run
```
docker run -d -p 5959:8000 \
    --name marmotteio \
    -e APP_NAME=Marmotte.io \
    -e APP_ENV=local \
    -e APP_DEBUG=true \
    -e APP_URL=http://0.0.0.0:5959 \
    -e DB_CONNECTION=sqlite \
    -e DB_DATABASE=/app/marmotte.sqlite \
    -e DB_FOREIGN_KEYS=true \
    -v $(pwd):/app \
    marmotteio/marmotteio:latest
```

/opt/docker/bin/entrypoint.d/default.sh: line 3: /app/start.sh: No such file or directory

My try at Docker Compose:

```
version: '3'
services:
  marmotteio:
    ports:
      - 5959:8000
    container_name: marmotteio
    environment:
      - APP_NAME=Marmotte.io
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=https:my.homelab.com
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/marmotte.sqlite
      - DB_FOREIGN_KEYS=true
    volumes:
      - /docker/marmotteio/app:/app
    image: marmotteio/marmotteio:latest
```
 /opt/docker/bin/entrypoint.d/default.sh: line 3: /app/start.sh: No such file or directory
